extends:
  - 'airbnb-typescript'
parserOptions:
  project: './asm/assembly/tsconfig.json'
rules:
  import/prefer-default-export:
    - off
  no-bitwise:
    - off
  import/no-cycle:
    - off
  no-param-reassign:
    - error
    - props: false
